### ISSUE TITLE
More info about the project

### ISSUE THREAD

**Issue by valtsu41** [Milinai/MonsterTD#1]
~~First!~~

You could probably add more info about the project, for example what language it uses and link to the itch.io page and stuff like that.

**Comment by Milinai** [comment]
I added that now.

**Comment by valtsu41** [comment]
Where?

**Comment by Milinai** [comment]
Oh, in the wiki...

**Comment by valtsu41** [comment]
Make readme ~~better~~ *richer* too?

**Comment by Milinai** [comment]
> Make readme better _richer_ too?

What should be added? Also, you can submit a PR.

**Comment by valtsu41** [comment]
It is good now.
